# Generated by Django 4.2.11 on 2025-06-23 01:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_title', models.CharField(default='Online Exam', max_length=200)),
                ('duration_minutes', models.IntegerField(default=120)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('head_misalignment', 'Head Misalignment'), ('eye_misalignment', 'Eye Misalignment'), ('mobile_detection', 'Mobile Detection'), ('lip_movement', 'Lip Movement'), ('emotion_detection', 'Emotion Detection'), ('session_start', 'Session Start'), ('session_end', 'Session End')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(default=dict)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sessions.examsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
