# Generated by Django 4.2.11 on 2025-06-23 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('head_misalignment', 'Head Misalignment'), ('eye_misalignment', 'Eye Misalignment'), ('mobile_detection', 'Mobile Detection'), ('lip_movement', 'Lip Movement'), ('emotion_detection', 'Emotion Detection')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
